#include "pico/stdlib.h"
#include "stdio.h"

// #include "hardware/adc.h"
// #include "hardware/spi.h"
// #include "hardware/dma.h"
// #include "hardware/interp.h"
// #include "hardware/timer.h"
// #include "hardware/watchdog.h"
#include "hardware/i2c.h"
#include "hardware/pio.h"
#include "hardware/gpio.h"
#include "hardware/clocks.h"
#include "math.h"
#include "stdbool.h"

#include "project_config.h"